Homepage for Apple Clone
Haroonabdulrazaq/Apple_Clone pull request #1
Opened 2020-05-16 12:07 UTC by Haroonabdulrazaq

- It includes 3 major section

1. The Hero section
2. The Grid Section
3. The Footer section
- I have fixed all Lints error I could find
Tested on Html validator and Stickler

2020-05-16 20:38 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved kindly implement the changes below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-16 20:38 UTC, lucasmazo32 commented on index.html
> +<!DOCTYPE html>
- [ ] Some of the items seem a little bit off. For instance, the navbar looks like it is thrown to the left. Maybe this has to do with the size of the screen. One piece of advice is that you use a max-width property on the body, so everything is with a specific size.

> ![image](https://user-images.githubusercontent.com/57414789/82129760-a5bb0680-978a-11ea-8d64-c98400ecd797.png)

2020-05-16 20:38 UTC, lucasmazo32 commented on index.html
> +        <div class="grid-4"></div>
- [ ] Please change this div tags for anchor tags (`<a></a>`). In the original webpage, they are links to another part of the page.

2020-05-16 20:38 UTC, lucasmazo32 commented on index.html
> +    </footer>
- [ ] If you could find a font closer to the original page that would be great! Also, please align the text in the left so they both start at the same point.

> ![image](https://user-images.githubusercontent.com/57414789/82129804-1cf09a80-978b-11ea-971e-ef78a2011b1d.png)

2020-05-18 20:45 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-18 20:50 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @Haroonabdulrazaq, great job :+1: Congratulations on fixing all the changes recommended by the previous TSE :smile: On this note, I hereby approve your project :100: 

You can go ahead and merge to master
Do not forget to submit the project completion form
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-18 21:03 UTC, Haroonabdulrazaq commented
Thank you

2020-05-18 21:12 UTC, merged